# Generated by Django 6.0.2 on 2026-02-22 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=255)),
                ('line_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255, verbose_name='State/Province/Region')),
                ('zip', models.CharField(max_length=255, verbose_name='Zip code')),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('consent', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PosterVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=255, verbose_name='Height in cm')),
                ('width', models.CharField(max_length=255, verbose_name='Width in cm')),
                ('listed', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price in SEK')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Dynamically added when instance is created.', max_length=255, null=True)),
                ('stripe_product_id', models.CharField(blank=True, help_text='Dynamically added when instance is created.', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wasteman.artwork')),
                ('height', models.CharField(max_length=255, verbose_name='Height in cm')),
                ('width', models.CharField(max_length=255, verbose_name='Width in cm')),
                ('listed', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wasteman.artwork', models.Model),
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wasteman.artwork')),
                ('ratio', models.CharField(choices=[('square', 'Square'), ('rectangle', 'Rectangle')], max_length=10)),
            ],
            bases=('wasteman.artwork',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.BooleanField(verbose_name='Agreed to terms of service.')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wasteman.address')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Optional User object')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wasteman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.BooleanField(verbose_name='Agreed to terms of service.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PosterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='wasteman.customer')),
                ('posters', models.ManyToManyField(to='wasteman.postervariation')),
                ('wasteman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='wasteman.wasteman')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='wasteman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasteman.wasteman'),
        ),
        migrations.AddField(
            model_name='postervariation',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='wasteman.poster'),
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('imagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wasteman.imagebase')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasteman.artwork')),
            ],
            bases=('wasteman.imagebase',),
        ),
        migrations.CreateModel(
            name='WastemanImage',
            fields=[
                ('imagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wasteman.imagebase')),
                ('wasteman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasteman.wasteman')),
            ],
            bases=('wasteman.imagebase',),
        ),
    ]
