# Generated by Django 6.0.2 on 2026-02-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posterorder',
            old_name='posters',
            new_name='variations',
        ),
        migrations.AddField(
            model_name='posterorder',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='unpaid', max_length=100),
        ),
        migrations.AddField(
            model_name='posterorder',
            name='stripe_checkout_session_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
