# Generated by Django 6.0.2 on 2026-02-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0003_address_first_name_address_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default='info@example.com', max_length=255),
            preserve_default=False,
        ),
    ]
