# Generated by Django 6.0.2 on 2026-02-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0004_address_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posterorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='posterorder',
            name='wasteman',
        ),
        migrations.AddField(
            model_name='posterorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='wasteman.address'),
        ),
    ]
