# Generated by Django 6.0.2 on 2026-02-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0005_remove_posterorder_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posterorder',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
