# Generated by Django 6.0.2 on 2026-02-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0006_alter_posterorder_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
