# Generated by Django 6.0.2 on 2026-02-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0007_alter_address_line_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterorder',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
