# Generated by Django 6.0.2 on 2026-02-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0008_posterorder_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posterorder',
            name='variations',
        ),
        migrations.CreateModel(
            name='PosterOrderVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poster_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='wasteman.posterorder')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_variations', to='wasteman.postervariation')),
            ],
        ),
    ]
