# Generated by Django 6.0.2 on 2026-03-03 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0009_remove_posterorder_variations_posterordervariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkimage',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wasteman.artwork'),
        ),
    ]
