# Generated by Django 6.0.2 on 2026-03-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0010_alter_artworkimage_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebase',
            name='image',
            field=models.ImageField(upload_to='artwork_images/'),
        ),
    ]
