# Generated by Django 6.0.2 on 2026-03-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0011_alter_imagebase_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
    ]
