# Generated by Django 6.0.2 on 2026-03-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0012_rename_first_name_address_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='58233', max_length=255, verbose_name='Postal code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Two letter country code'),
        ),
    ]
