# Generated by Django 6.0.2 on 2026-03-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0013_remove_address_zip_address_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='line_1',
            new_name='line1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='line_2',
            new_name='line2',
        ),
    ]
