# Generated by Django 6.0.2 on 2026-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0014_rename_line_1_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteremail',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsletteremail',
            name='consent',
            field=models.BooleanField(default=True, verbose_name='I want to receive marketing emails'),
        ),
    ]
