# Generated by Django 6.0.2 on 2026-03-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteman', '0015_newsletteremail_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletteremail',
            old_name='verified',
            new_name='confirmed',
        ),
        migrations.AlterField(
            model_name='newsletteremail',
            name='consent',
            field=models.BooleanField(default=True, verbose_name='I want to receive newsletters'),
        ),
    ]
